USE [HelaMedical]
GO

CREATE TABLE [dbo].[Alcoes](
	[Id] [int]  NULL,
	[FIO] [nvarchar](max) NULL,
	[Sex] [nvarchar](max) NULL,
	[Date] [nvarchar](max) NULL,
	[RegionCenterBLR] [nvarchar](max) NULL,
	[RaenCenterBLR] [nvarchar](max) NULL,
	[Life] [nvarchar](max) NULL,
	[Age] [nvarchar](max) NULL,
	[FamilyStatus] [nvarchar](max) NULL,
	[CostOfKids] [nvarchar](max) NULL,
	[FamilyComposition] [nvarchar](max) NULL,
	[Education] [nvarchar](max) NULL,
	[Profession] [nvarchar](max) NULL,
	[TheSkillLevelOfTheProfession] [nvarchar](max) NULL,
	[AddressOfRegistration] [nvarchar](max) NULL,
	[AddressAtTheTimeOfDeath] [nvarchar](max) NULL,
	[DataOfRegistration] [nvarchar](max) NULL,
	[ReRegistrationData] [nvarchar](max) NULL,
	[TypeOfRegistration] [nvarchar](max) NULL,
	[Heredity] [nvarchar](max) NULL,
	[DisabilityGroup] [nvarchar](max) NULL,
	[DisabilityStatus] [nvarchar](max) NULL,
	[ReasonForDisability] [nvarchar](max) NULL,
	[WorksStatus] [nvarchar](max) NULL,
	[AdmOtv] [nvarchar](max) NULL,
	[UgOtv] [nvarchar](max) NULL,
	[DlitsMLS] [nvarchar](max) NULL,
	[Stat107] [nvarchar](max) NULL,
	[StatUKRB] [nvarchar](max) NULL,
	[RodPrav] [nvarchar](max) NULL,
	[NomLTP] [nvarchar](max) NULL,
	[LTPKol] [nvarchar](max) NULL,
	[Hospitel] [nvarchar](max) NULL,
	[EK] [nvarchar](max) NULL,
	[DateOfDeregistration] [nvarchar](max) NULL,
	[DateOfDead] [nvarchar](max) NULL,
	[PlaceOfDead] [nvarchar](max) NULL,
	[DeathCertificate] [nvarchar](max) NULL,
	[CauseOfDead] [nvarchar](max) NULL,
	[DeathCategory] [nvarchar](max) NULL,
	[OpeningPlace] [nvarchar](max) NULL,
	[HistoryOfParasucicides] [nvarchar](max) NULL,
	[FeaturesOfObservation] [nvarchar](max) NULL,
	[ExperienceAbuse] [nvarchar](max) NULL,
	[AlcoholicDrinks] [nvarchar](max) NULL,
	[IK] [nvarchar](max) NULL,
	[DrugDiagnosisAlc] [nvarchar](max) NULL,
	[AgeOfDead] [nvarchar](max) NULL,
	[AgeOfRegistration] [nvarchar](max) NULL,
	[Registrotor] [nvarchar](max) NULL,)
GO


